# -*- coding: utf-8 -*-
"""vehicle_fuel_efficiency_deployement.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SAu9P0_9SNkNARmeI0MnvWpdbNE5DAdj
"""

import streamlit as st
import pandas as pd
import joblib

# Load model and encoder
model = joblib.load("vehicle_fuel_efficiency_model.pkl")
encoder = joblib.load("label_encoder_vehicle.pkl")

st.set_page_config(page_title="Vehicle Fuel Efficiency", page_icon="🚗")

st.title("🚗 Vehicle Fuel Efficiency Prediction System")
st.write("Enter vehicle details to estimate fuel efficiency (MPG).")

st.subheader("Vehicle Specifications")

col1, col2 = st.columns(2)

with col1:
    cylinders = st.slider("Cylinders", 3, 12, 4)
    displacement = st.number_input("Displacement", min_value=0.0)
    horsepower = st.number_input("Horsepower", min_value=0.0)
    weight = st.number_input("Weight", min_value=0.0)

with col2:
    acceleration = st.number_input("Acceleration", min_value=0.0)
    model_year = st.slider("Model Year", 70, 85, 76)
    origin = st.selectbox("Origin", ["USA", "Europe", "Japan"])

# Convert origin to numeric
origin_map = {"USA": 1, "Europe": 2, "Japan": 3}
origin_value = origin_map[origin]

# Car name dropdown from encoder classes
car_name = st.selectbox("Car Name", encoder.classes_)
car_name_encoded = encoder.transform([car_name])[0]

# Create dataframe
input_data = pd.DataFrame({
    "cylinders": [cylinders],
    "displacement": [displacement],
    "horsepower": [horsepower],
    "weight": [weight],
    "acceleration": [acceleration],
    "model year": [model_year],
    "origin": [origin_value],
    "car name": [car_name_encoded]
})

# Prediction
if st.button("Predict Fuel Efficiency"):
    prediction = model.predict(input_data)
    st.success(f"Estimated Fuel Efficiency: {prediction[0]:.2f} MPG")
